### ISSUE TITLE
V3.6.2 数学公式预览未生效

### ISSUE THREAD

**Issue by wenhuancui** [88250/symphony#12]
数学公式预览无效
![image](https://user-images.githubusercontent.com/4651913/78225179-5f705780-74fc-11ea-895d-f0d33fdf493a.png)

但所见即所得正常
![image](https://user-images.githubusercontent.com/4651913/78225271-862e8e00-74fc-11ea-8ba4-f32bda9e9264.png)

**Comment by 88250** [comment]
服务端渲染需要[开启 Lute HTTP 支持](https://hacpai.com/article/1569240189601)。
