### ISSUE TITLE
可以给一个单元测试的demo

### ISSUE THREAD

**Issue by yishanchuan** [88250/symphony#15]
### 你在什么场景下需要该功能？

我在自定义一些service时，希望可以使用类似SpringBootTest的单元测试，可以很大程度上方便做测试覆盖，而不是仅能通过processor的返回值确定下层的repository、service等的正确性。

### 其他信息

可能也有过开发，尝试过检索黑客派，但是没有发现合适的相关文档
欢迎任何指教，非常感谢

**Comment by 88250** [comment]
你好，可参考一下 [Solo](https://github.com/88250/solo) 中的测试用例，用的也是 Latke 框架。
