### ISSUE TITLE
仅支持通过 [github] 进行登录，不支持注册

### ISSUE THREAD

**Issue by liudonghua123** [88250/symphony#17]
### 描述问题

访问 https://hacpai.com/ ，点击`使用 GitHub 进行登录` 提示 `仅支持通过 [github] 进行登录，不支持注册`

### 期待的结果

可以正常使用Github OAuth认证登陆

### 截屏或录像

![animation1](https://user-images.githubusercontent.com/2276718/81575057-2b306680-93d9-11ea-9727-64d4c9868aea.gif)

### 其他信息

无

**Comment by 88250** [comment]
目前黑客派上所有的第三方 OAuth 仅支持登录，不支持注册。请在设置中绑定 GitHub 后再使用 OAuth 方式登录。

https://hacpai.com/settings/account
