### ISSUE TITLE
修改密码报错

### ISSUE THREAD

**Issue by ZhengChengGui** [88250/symphony#25]
无法修改密码（附log截图）

![1](https://user-images.githubusercontent.com/24267048/83318940-335b2380-a26c-11ea-89fd-d9c69d6c8bb3.jpg)
![2](https://user-images.githubusercontent.com/24267048/83318941-37874100-a26c-11ea-95ac-87a86527abec.jpg)

**Comment by 88250** [comment]
感谢反馈，稍后修复。
