### ISSUE TITLE
Mardown preview error

### ISSUE THREAD

**Issue by Rin57TH4** [88250/symphony#29]
Symphony v3.6.3
Preview error

![sym](https://user-images.githubusercontent.com/16234748/84728718-150b5c80-afbc-11ea-8c35-28a724a3a702.PNG)

**Comment by 88250** [comment]
你好，请看[安装指南 FAQ](https://hacpai.com/article/1486188905847#FAQ)。

**Comment by Rin57TH4** [comment]
I checked the network and everything is working fine.
When I exit the preview mode, it's ok
![Capture2](https://user-images.githubusercontent.com/16234748/84731432-04aab000-afc3-11ea-972b-b41c6813d3b8.PNG)
![Capture3](https://user-images.githubusercontent.com/16234748/84731550-65d28380-afc3-11ea-8e14-da93e0423303.PNG)

**Comment by 88250** [comment]
预览时走的是服务端渲染，所以需要 Lute HTTP 提供 Markdown 渲染支持。编辑时走的是 Vditor 编辑器自身的渲染，已经支持 GFM 等 Markdown 扩展语法。

**Comment by Rin57TH4** [comment]
Thank, I have solved the problem.
