### ISSUE TITLE
D大～，下一个版本什么时候发布？

### ISSUE THREAD

**Issue by cbamls** [88250/symphony#41]
期待好久了～

**Comment by 88250** [comment]
估计明年第一季度内，最近在忙[其他项目](https://github.com/siyuan-note/siyuan)，非常抱歉啊……

**Comment by cbamls** [comment]
收到！继续期待前端改版
---原始邮件---
发件人:&quot;D&quot;<notifications@github.com&gt;
发送时间:2020年11月5日 星期四 上午0:14
收件人:&quot;88250/symphony&quot;<symphony@noreply.github.com&gt;
抄送:&quot;cbamls&quot;<756029571@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;
主题:Re: [88250/symphony] D大～，下一个版本什么时候发布？ (#41)



估计明年第一季度内，最近在忙其他项目，非常抱歉啊……

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;authored&nbsp;the&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.
