### ISSUE TITLE
Provide mechanism for non-Chinese supporters to pay

### ISSUE THREAD

**Issue by ms3056** [88250/symphony#43]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
I love this product - and I would like to contribute to purchase a lifetime license. I could not figure out a way to do this. Please let me know if there is another way to contribute to activate the lifetime license.

**Comment by 88250** [comment]
Hello, we support purchase license via PayPal, price is $2000, if you need it please send an email to support@b3log.org, we will create a PayPal email order for you, thanks.
