### ISSUE TITLE
关于商业版和社区版

### ISSUE THREAD

**Issue by ifu25** [88250/symphony#44]
看了商业版的对比，发现放在第一的是安全性，我个人是很难接受这一点的：
个人观点认为即便是免费社区版，也不应该在【安全性】上做妥协！

商业版可以在功能性上做扩充，而不应该把这个做为卖点。

![20210114_101107](https://user-images.githubusercontent.com/5575008/104535341-f7d16600-5650-11eb-97db-d8635e56f9da.png)

**Comment by 88250** [comment]
谢谢关注，社区版是完全开源的，请自行完善。
