### ISSUE TITLE
在标签树上点击多个标签时，无法实现切换，只是点一个加一个

### ISSUE THREAD

**Issue by wangminli** [88250/symphony#57]
### 描述问题 Describe the problem

在标签树上点击多个标签时，无法实现切换，只是点一个加一个

### 期待的结果 Expected result

期待点击一个标签就切换一个标签，而不是多个标签累加在一块进行检索

### 截屏或录像 Screenshot or video
![图片](https://user-images.githubusercontent.com/5483360/134711945-73ace49b-6b30-4da3-af7e-fd091fca3153.png)

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
* 累加搜索是特性
* 取消标签的话可以重复再点击同样的标签

PS 提错仓库了，思源笔记 https://github.com/siyuan-note/siyuan
