### ISSUE TITLE
移动端跳转到指定笔记

### ISSUE THREAD

**Issue by chengliangzhang** [88250/symphony#68]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
前置条件：同时使用PC端和安卓移动端，在启动思源时会进行云同步。在PC端添加了一条笔记
操作：
1. 在PC端复制了新笔记的块超链接，通过第三方软件发送到了移动端
2. 在移动端点击此链接
预期：和PC端一样，可以打开思源笔记并定位到链接的笔记
实际：可以打开思源笔记，但定位到最后打开的笔记，而非链接的笔记

**Comment by 88250** [comment]
提错项目了吧。
