### ISSUE TITLE
开发的时候没有热重载

### ISSUE THREAD

**Issue by 14790897** [88250/symphony#80]
需要freemaker的热重载  (❁´◡`❁)(●'◡'●)╰(*°▽°*)╯

**Comment by 14790897** [comment]
大佬在吗

**Comment by 88250** [comment]
Freemarker 模板我记得开发环境（mode=dev）就是热加载的，是不是改了样式没有生效？

**Comment by 14790897** [comment]
![image](https://github.com/88250/symphony/assets/121866954/581c373b-7a92-4fad-8837-11804de554fd)
我是在Ubuntu 服务器的tmux里运行的，现在更改.ftl文件不会自动应用

**Comment by 88250** [comment]
服务器日志一开始能看到这行吗？

```
[WARN ]-[2023-11-10 21:30:19]-[org.b3log.latke.Latkes:713]: !!!!Runtime mode is [DEVELOPMENT], please make sure configured it with [PRODUCTION] in latke.properties if deployed on production environment!!!!
```

**Comment by 14790897** [comment]
![image](https://github.com/88250/symphony/assets/121866954/af08de07-bea6-457d-93f9-be5792e5b89c)
有的

**Comment by 88250** [comment]
抱歉，我记错了，这个和开发/生产模式没有关系。

我猜测你可能是修改错位置了，请参考 https://github.com/88250/symphony/blob/master/src/main/java/org/b3log/symphony/util/Templates.java

**Comment by 14790897** [comment]
我修改的确实是resources文件夹下的ftl文件，我明天再问问别人

**Comment by 14790897** [comment]
大佬，我使用下面的代码启动
```
mvn package
java -cp "target/symphony/lib/*;target/symphony" org.b3log.symphony.Server
```

修改resources目录下的代码不能立即生效，需要重新运行上面的代码才可以生效

**Comment by 14790897** [comment]
我发现idea是可以热重载，但vs code和命令行不行，为什么？

**Comment by 14790897** [comment]
👀

**Comment by 88250** [comment]
大概是类加载机制不一样吧，可以参考上面的代码调试看看。

**Comment by 14790897** [comment]
好的，我再想想
