### ISSUE TITLE
Find a trigger for log4j2 remote command execution in symphony 3.6.3

### ISSUE THREAD

**Issue by By-Yexing** [88250/symphony#82]
In symphony 3.6.3 and earlier, the use of an insecure log4j version resulted in a remote command execution risk. In the course of actual testing, a vulnerability trigger was found:
![b62f304d7843a47d9c9236beb71c448](https://github.com/88250/symphony/assets/107806521/9e58e85b-2dad-41cc-a48e-ca30bcadb5ac)
![d4627af0ccf00c20f8e4f183cf0e1b3](https://github.com/88250/symphony/assets/107806521/18fef494-79da-4304-8a3d-93b27c33988c)
Vulnerability interface: "/activity/character/submit"
![565bf4fc77ba97767a4655d53552dd6](https://github.com/88250/symphony/assets/107806521/affdedab-be6c-4b87-95f6-9bf1ef0f78aa)
![de8fd3138b80ba7d411a64300cd0a43](https://github.com/88250/symphony/assets/107806521/9245b4d0-5756-4ae7-be2f-949671338634)
This can eventually cause an attacker to take over the server.
![ea10bf5cf42afcfb88320bbcd0cff1c](https://github.com/88250/symphony/assets/107806521/b3b312af-8fb8-44c9-9e64-391fa799601e)
At present, there are still a large number of servers in the public network that have not been upgraded to 3.6.4.

**Comment by 88250** [comment]
Thanks for reporting this issue. We have upgraded the log4j dependency in the latest version.
