### ISSUE TITLE
npm run dev/build都不能用

### ISSUE THREAD

**Issue by xuanxuan159** [88250/symphony#87]
### 描述问题 Describe the problem

npm run dev 命令执行到Starting 'sassProcessWatch'... 这一行就停止滚动了。
npm run build 命令执行后屏幕不显示任何内容。

### 期待的结果 Expected result

前者出现浏览器窗口，后者出现编译产物

### 版本环境 Version environment

* 版本 Version：node 16 latest
* 操作系统 Operating system：windows11
* 浏览器（如果使用）Browser (if used)：no

**Comment by Vanessa219** [comment]
是不是 sass 没有安装成功？重新安装再试试

**Comment by xuanxuan159** [comment]
还是有问题，具体见视频

https://github.com/88250/symphony/assets/97965017/e8a6072e-02c1-4e76-81d9-b8b4242908e0


https://github.com/88250/symphony/assets/97965017/eb988afc-5633-4beb-abc9-0d8035be9363


https://github.com/88250/symphony/assets/97965017/47eb97c8-d4e3-4aec-9859-ece2c061d0a2

<img width="620" alt="屏幕截图 2024-03-07 211422" src="https://github.com/88250/symphony/assets/97965017/0a4c1905-0d90-47b2-8dee-4e8c76f869b5">

图片里面也没有dist目录说明npm run build无效

**Comment by Vanessa219** [comment]
看上去是正常的，dev 是需要监听文件变化，因此进程不会结束。build 后目录为：

<img width="415" alt="image" src="https://github.com/88250/symphony/assets/970828/e7f24a8f-8baf-457e-8ee1-4964cd60d737">
