### ISSUE TITLE
文件名在页面的显示问题！

### ISSUE THREAD

**Issue by mieyeaa** [88250/symphony#92]
文件名在页面显示和标题的样式太像，希望能优化下，做到和标题样式有明显区分。

**Comment by 88250** [comment]
外观样式请自行修改，谢谢。

**Comment by mieyeaa** [comment]
> 外观样式请自行修改，谢谢。

不是修改标题样式，是修改文件名样式，文件名样式貌似不没有自行修改样式的功能吧！

**Comment by mieyeaa** [comment]
> > 外观样式请自行修改，谢谢。
> 
> 不是修改标题样式，是修改文件名样式，文件名样式貌似不没有自行修改样式的功能吧！

抱歉，思源里面不叫文件名，是文档名。

**Comment by 88250** [comment]
你提错项目了吧，这个不是思源笔记项目。

**Comment by mieyeaa** [comment]
> 你提错项目了吧，这个不是思源笔记项目。

哎，还真是。那我去思源那再提一下？

**Comment by 88250** [comment]
截个图我看下，只看文字描述不清晰哦。

**Comment by mieyeaa** [comment]
> 截个图我看下，只看文字描述不清晰哦。

![123](https://github.com/88250/symphony/assets/59656688/7005ede7-5fe2-4d86-9047-9730d7040db7)

**Comment by 88250** [comment]
这个还是有一些区分的，如果还是觉得不行的话可以考虑通过自定义 CSS 修改，谢谢。

**Comment by mieyeaa** [comment]
> 这个还是有一些区分的，如果还是觉得不行的话可以考虑通过自定义 CSS 修改，谢谢。

区别不大啊，要我修改，那我还反馈干嘛！

**Comment by mieyeaa** [comment]
> 这个还是有一些区分的，如果还是觉得不行的话可以考虑通过自定义 CSS 修改，谢谢。

区别不大啊，要我修改，那我还反馈干嘛！
