### ISSUE TITLE
请求优化搜索功能

### ISSUE THREAD

**Issue by SaXz2** [88250/symphony#98]
### 描述问题 Describe the problem
目前的搜索逻辑是以块为单位，但是大多数的时候是根据文档名称+文档内内容进行复合搜索的，这导致现在的搜索如果搜索标题+文档内容是检索不出来的
以下是Obsidian和思源的检索对比，希望作者大大添加一下这种功能，内容多起来不容易进行检索查找
![image](https://github.com/user-attachments/assets/0e16f4c9-4161-4bae-988e-0d7ab28fdd02)
![image](https://github.com/user-attachments/assets/d0fe0105-bdbc-407b-97cf-bbb7368c8e50)

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，你提错项目了，这个应该提到 https://github.com/siyuan-note/siyuan 上。

另外，这个问题已经有记录了，请关注 https://github.com/siyuan-note/siyuan/issues/10584
